const schema = {
  type: 'object',
  required: [
    'customerNumber',
    'customerName',
    'contactLastName',
    'contactFirstName',
    'phone',
    'addressLine1',
    'city',
    'country',
    'salesRepEmployeeNumber',
  ],

  properties: {
    customerNumber: { type: 'integer', minimum: 1 },
    customerName: { type: 'string', minLength: 5, maxLength: 50 },
    contactLastName: { type: 'string', minLength: 3, maxLength: 50 },
    contactFirstName: { type: 'string', minLength: 3, maxLength: 50 },
    phone: { type: 'string', minLength: 8, maxLength: 20 },
    addressLine1: { type: 'string', minLength: 10, maxLength: 50 },
    addressLine2: {
      type: ['string', 'null'],
      minLength: 10,
      maxLength: 50,
    },
    city: { type: 'string', minLength: 2, maxLength: 50 },
    state: { type: ['string', 'null'], minLength: 2, maxLength: 50 },
    postalCode: { type: ['string', 'null'], minLength: 5, maxLength: 15 },
    country: { type: 'string', minLength: 2, maxLength: 50 },
    salesRepEmployeeNumber: { type: ['integer', 'null'], minimum: 1 },
    creditLimit: {
      type: ['number', 'null'],
      minimum: 0,
      maximum: 10000000000,
    },
    role: 4,
  },
};

const customer = {
  customerNumber: 602,
  customerName: 'Atelier graphique',
  contactLastName: 'Schmitt',
  contactFirstName: 'Carine ',
  phone: '40.32.2555',
  addressLine1: '54, rue Royale',
  addressLine2: null,
  city: 'Nantes',
  state: null,
  postalCode: '44000',
  country: 'France',
  salesRepEmployeeNumber: 1370,
  creditLimit: 21000,
};

const customers = [
  {
    customerNumber: 602,
    customerName: 'Atelier graphique',
    contactLastName: 'Schmitt',
    contactFirstName: 'Carine ',
    phone: '40.32.2555',
    addressLine1: '54, rue Royale',
    addressLine2: null,
    city: 'Nantes',
    state: null,
    postalCode: '44000',
    country: 'France',
    salesRepEmployeeNumber: 1370,
    creditLimit: 21000,
  },
  {
    customerNumber: 603,
    customerName: 'Atelier graphique',
    contactLastName: 'Schmitt',
    contactFirstName: 'Carine ',
    phone: '40.32.2555',
    addressLine1: '54, rue Royale',
    addressLine2: null,
    city: 'Nantes',
    state: null,
    postalCode: '44000',
    country: 'France',
    salesRepEmployeeNumber: 1371,
    creditLimit: 21000,
  }, {
    customerNumber: 604,
    customerName: 'Atelier graphique',
    contactLastName: 'Schmitt',
    contactFirstName: 'Carine ',
    phone: '40.32.2555',
    addressLine1: '54, rue Royale',
    addressLine2: null,
    city: 'Nantes',
    state: null,
    postalCode: '44000',
    country: 'France',
    salesRepEmployeeNumber: 1372,
    creditLimit: 21000,
  },
];

const listOfEmployeeNumber = [
  { employeeNumber: 1371 },
  { employeeNumber: 1372 },
];

const customerByEmployeeNum = {
  total: 2,
  data: [
    {
      customerNumber: 603,
      customerName: 'Atelier graphique',
      contactLastName: 'Schmitt',
      contactFirstName: 'Carine ',
      phone: '40.32.2555',
      addressLine1: '54, rue Royale',
      addressLine2: null,
      city: 'Nantes',
      state: null,
      postalCode: '44000',
      country: 'France',
      salesRepEmployeeNumber: 1371,
      creditLimit: 21000,
    }, {
      customerNumber: 604,
      customerName: 'Atelier graphique',
      contactLastName: 'Schmitt',
      contactFirstName: 'Carine ',
      phone: '40.32.2555',
      addressLine1: '54, rue Royale',
      addressLine2: null,
      city: 'Nantes',
      state: null,
      postalCode: '44000',
      country: 'France',
      salesRepEmployeeNumber: 1372,
      creditLimit: 21000,
    },
  ],
};

const customerById = {
  customerNumber: 603,
  customerName: 'Atelier graphique',
  contactLastName: 'Schmitt',
  contactFirstName: 'Carine ',
  phone: '40.32.2555',
  addressLine1: '54, rue Royale',
  addressLine2: null,
  city: 'Nantes',
  state: null,
  postalCode: '44000',
  country: 'France',
  salesRepEmployeeNumber: 1371,
  creditLimit: 21000,
};

const customerUpdate = {
  customerNumber: 602,
  customerName: 'Atelier graphique UPDATE',
  contactLastName: 'Schmitt',
  contactFirstName: 'Carine ',
  phone: '40.32.2555',
  addressLine1: '54, rue Royale',
  addressLine2: null,
  city: 'Nantes',
  state: null,
  postalCode: '44000',
  country: 'France',
  salesRepEmployeeNumber: 1371,
  creditLimit: 21000,
};

const notAllowedCustomer = {
  customerNumber: 600,
  customerName: 'Atelier graphique UPDATE',
  contactLastName: 'Schmitt',
  contactFirstName: 'Carine ',
  phone: '40.32.2555',
  addressLine1: '54, rue Royale',
  addressLine2: null,
  city: 'Nantes',
  state: null,
  postalCode: '44000',
  country: 'France',
  salesRepEmployeeNumber: 1000,
  creditLimit: 21000,
};

const orderNumbers = [
  { orderNumber: 10124 },
  { orderNumber: 10278 },
  { orderNumber: 10346 },
];
export default {
  schema,
  customers,
  customer,
  customerByEmployeeNum,
  listOfEmployeeNumber,
  customerById,
  customerUpdate,
  notAllowedCustomer,
  orderNumbers,
};
